version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hrx-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hrx
      POSTGRES_PASSWORD: hrx123
      POSTGRES_DB: hrx
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
